### ISSUE TITLE
Why we have to use composer with simple php class?

### ISSUE THREAD

**Issue by equaser** [InitPHP/Database#1]
Hi,
Why we have to use composer as apposed to putting php files in a folder and start using them?
Isn't this a simple php class? or people simply want to make things harder in order to impress others?

**Comment by muhammetsafak** [comment]
Hi,
Composer is important in this library for two things;
- I can't say that this library has no bugs. I do a quick update if there's a bug I come across or someone reports. Composer does a good job of distributing updates.
- Composer PSR-4 autoloader class. 

If you have your own PSR-4 class; For the `\InitPHP\Database` namespace prefix, saving the `src/` directory of this repo is enough for you to use it.

**Comment by equaser** [comment]
but you added another  requirement psf-4. if we have a class book.php and a few included file like inc.book1.php and inc.book2.php why should we use or "autoload" it . wow. I wonder how world is moving slowly by adding obstacles.  I have written  over 500k line or more php codes with classes none needs composer or anything else. just dump them in a directory and include them in a your php and they work. 
make it like that. it would make life easier, efficient. may be 1000s other came to this repository and passed because you made hard.

**Comment by muhammetsafak** [comment]
Keeping the entire library in one file makes the development process a torture. The simplicity of this library comes from the fact that it does not contain only the structures required in the development environment, such as Migration and Seeder. Including a PHP file in the script will not cause as big a performance loss as you think. If you do not want to use PSR-4 with performance concerns; `src/init.php` will include necessary files. It's not good to have 500k lines of code written in one file. The file size grows and PHP's inclusion/processing time increases. When an error occurs, it takes more time to detect and fix it. 500k lines of code are also difficult to read and understand. Moreover, it is necessary to have good hardware to read/open that file comfortably. Thank you for your attention, but to make them a single PHP file; It would be opening the door of hell for me. :)

**Comment by equaser** [comment]
Hi, Thank you for your reply. I did not say all the code should be in one file. I have tones of folders and over 100 files. none needs another tool . All are included or trait used by classes.
