### ISSUE TITLE
toAssoc returns a single array when result has 1 result

### ISSUE THREAD

**Issue by levizwannah** [InitPHP/Database#17]
I noticed that the Result->toAssoc() function returns a single array when the result has 1 row. That is, the array returned is not an array of associative arrays. So it makes it inconsistent when looping over the values. For example.

```php
DB::table('test')->where('name', 1)->get()->toAssoc(); // returns
// [ 'name' => 'test ]

// next
DB::table('test')->get()->toAssoc(); // returns
//[ [ 'name' => 'test'], ['name' => 'test2'], ... ]
  
```

**Comment by muhammetsafak** [comment]
Thanks for your return. I will deal with it as soon as possible.

**Comment by muhammetsafak** [comment]
The behavior of methods such as `toAssoc()` or `toArray()` may vary depending on the number of rows returned. Instead, with methods such as `asAssoc()` or `asArray()` that only change the data type to be returned; You can use `row()` or `rows()` methods.

Example : 
```php
DB::table('test')->get()->asAssoc()->row(); // returns
// [ 'name' => 'test ]

DB::table('test')->get()->asAssoc()->rows(); // returns
//[ [ 'name' => 'test'], ['name' => 'test2'], ... ]
  
```
